Fix issue with groups being automatically opened when toggled
OpenSpace/OpenSpace-WebGuiFrontend pull request #149
Opened 2023-06-05 21:37 UTC by ylvaselling

Also rewrote PropertyOwner to a functional component while I was at it, and optimized the Group component so it re-renders less.

2023-06-07 07:41 UTC, alexanderbock approved these changes

2023-06-07 08:14 UTC, WeirdRubberDuck requested changes
This should be fixed. Also, clicking a focus button crashes the UI

![image](https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/assets/8808894/59023b47-23a1-40f4-bf19-c7b43886b5e3)

2023-06-08 11:34 UTC, WeirdRubberDuck approved these changes

2023-06-08 11:39 UTC, WeirdRubberDuck commented
Great :)

2023-06-08 18:08 UTC, merged