Added subscribers and other details to flightController
OpenSpace/OpenSpace-WebGuiFrontend pull request #199
Opened 2024-09-03 03:02 UTC by GPayne

Fix for [OpenSpace issue#3397](https://github.com/OpenSpace/OpenSpace/issues/3397)

2024-09-06 08:54 UTC, ylvaselling commented on src/api/Middleware/flightController.js
> +let nSubscribers = 0;
Removed unused imports
```
import actionTypes from '../Actions/actionTypes';
import api from '../api';

let topic = undefined;
let nSubscribers = 0;
```

2024-09-06 08:54 UTC, ylvaselling commented on src/api/Middleware/flightController.js
> +  }
```suggestion
async function connectToFlightControllerTopic(store) {
  topic = api.startTopic(
    'flightcontroller',
    {
      type: "connect"
    }
  );
}

const unsubscribe = () => {
  if (!topic) {
    return;
  }
  topic.talk({
    event: 'disconnect'
  });
  topic.cancel();
}
```

2024-09-06 08:54 UTC, ylvaselling commented on src/api/Middleware/flightController.js
> +  }
There is no "stop_subscription" or "refresh" in the `flightcontrollertopic.cpp` :)

2024-09-06 08:54 UTC, ylvaselling commented on src/api/Middleware/flightController.js
>        break;
```suggestion
```

2024-09-06 11:51 UTC, WeirdRubberDuck requested changes
I'm quite unaware of the context for this PR, so can't say much about why the subscribers are needed or comment on that part. But it seems to me like it does not actually fix the issue https://github.com/OpenSpace/OpenSpace/issues/3397? I managed to reproduce it even with this update, by following the steps in the issue

Otherwise, I added some comments to make the code comply to our eslint settings. I recommend installing the ESLint plugin for VS Code, to more easily catch these errors during the coding

2024-09-06 11:51 UTC, WeirdRubberDuck commented on src/api/Middleware/flightController.js
> +async function connectToFlightControllerTopic(store) {
```suggestion
async function connectToFlightControllerTopic() {
```

2024-09-06 11:51 UTC, WeirdRubberDuck commented on src/api/Middleware/flightController.js
> +export const flightController = store => next => action => {
```suggestion
export const flightController = (store) => (next) => (action) => {
```
To comply with out linting settings

2024-09-06 11:51 UTC, WeirdRubberDuck commented on src/api/Middleware/flightController.js
> +let topic = undefined;
```suggestion
let topic;
```

This does not have to be initialized as undefined, and our linting currently warns about it.

2024-09-06 11:51 UTC, WeirdRubberDuck commented on src/api/Middleware/flightController.js
> +import { actionTypes } from '../Actions/actionTypes';
```suggestion
import actionTypes from '../Actions/actionTypes';
```
This currently does not work

2024-10-16 16:43 UTC, GPayne commented
Retracting this PR because my test results were a false positive. I'm unable to reproduce the fix, probably due to my original test setup being flawed somehow.
A rewrite of this frontend code is currently in progress, and [this issue](https://github.com/OpenSpace/OpenSpace/issues/3397) may well be fixed as part of that effort.

2024-10-16 16:43 UTC, closed without merging